# Generated by Neurodocker and Reproenv.

FROM ghcr.io/vferat/smriprep:0.19.1-dev
ENV LANG="en_US.UTF-8" \
    LC_ALL="en_US.UTF-8" \
    ND_ENTRYPOINT="/neurodocker/startup.sh"
RUN export ND_ENTRYPOINT="/neurodocker/startup.sh" \
    && apt-get update -qq \
    && apt-get install -y -q --no-install-recommends \
           apt-utils \
           bzip2 \
           ca-certificates \
           curl \
           locales \
           unzip \
    && rm -rf /var/lib/apt/lists/* \
    && sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen \
    && dpkg-reconfigure --frontend=noninteractive locales \
    && update-locale LANG="en_US.UTF-8" \
    && chmod 777 /opt && chmod a+s /opt \
    && mkdir -p /neurodocker \
    && if [ ! -f "$ND_ENTRYPOINT" ]; then \
         echo '#!/usr/bin/env bash' >> "$ND_ENTRYPOINT" \
    &&   echo 'set -e' >> "$ND_ENTRYPOINT" \
    &&   echo 'export USER="${USER:=`whoami`}"' >> "$ND_ENTRYPOINT" \
    &&   echo 'if [ -n "$1" ]; then "$@"; else /usr/bin/env bash; fi' >> "$ND_ENTRYPOINT"; \
    fi \
    && chmod -R 777 /neurodocker && chmod a+s /neurodocker
RUN apt-get update -qq \
           && apt-get install -y -q --no-install-recommends \
                  ffmpeg \
                  graphviz \
                  libsm6 \
                  libxext6 \
                  x11-utils \
                  xvfb \
           && rm -rf /var/lib/apt/lists/*
RUN apt-get update -qq \
           && apt-get install -y -q --no-install-recommends \
                  graphviz \
                  libegl1 \
                  libgl1-mesa-dri \
                  libosmesa6 \
           && rm -rf /var/lib/apt/lists/*
RUN micromamba install -y -n smriprep -c conda-forge 'vtk>=9.3=*osmesa*' && micromamba clean --all --yes
RUN micromamba install -y -n smriprep -c conda-forge 'nodejs>=20' && micromamba clean --all --yes
COPY [".", \
      "/meeg-pipelines"]
RUN micromamba run -n smriprep pip install --no-cache-dir -e /meeg-pipelines[all]
COPY ["./docker/entrypoint.sh", \
      "/usr/local/bin/entrypoint.sh"]
RUN chmod +x /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
RUN mkdir -p /out /scratch

# Save specification to JSON.
RUN printf '{ \
  "pkg_manager": "apt", \
  "existing_users": [ \
    "root" \
  ], \
  "instructions": [ \
    { \
      "name": "from_", \
      "kwds": { \
        "base_image": "ghcr.io/vferat/smriprep:0.19.1-dev" \
      } \
    }, \
    { \
      "name": "env", \
      "kwds": { \
        "LANG": "en_US.UTF-8", \
        "LC_ALL": "en_US.UTF-8", \
        "ND_ENTRYPOINT": "/neurodocker/startup.sh" \
      } \
    }, \
    { \
      "name": "run", \
      "kwds": { \
        "command": "export ND_ENTRYPOINT=\\"/neurodocker/startup.sh\\"\\napt-get update -qq\\napt-get install -y -q --no-install-recommends \\\\\\n    apt-utils \\\\\\n    bzip2 \\\\\\n    ca-certificates \\\\\\n    curl \\\\\\n    locales \\\\\\n    unzip\\nrm -rf /var/lib/apt/lists/*\\nsed -i -e '"'"'s/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/'"'"' /etc/locale.gen\\ndpkg-reconfigure --frontend=noninteractive locales\\nupdate-locale LANG=\\"en_US.UTF-8\\"\\nchmod 777 /opt && chmod a+s /opt\\nmkdir -p /neurodocker\\nif [ ! -f \\"$ND_ENTRYPOINT\\" ]; then\\n  echo '"'"'#!/usr/bin/env bash'"'"' >> \\"$ND_ENTRYPOINT\\"\\n  echo '"'"'set -e'"'"' >> \\"$ND_ENTRYPOINT\\"\\n  echo '"'"'export USER=\\"${USER:=`whoami`}\\"'"'"' >> \\"$ND_ENTRYPOINT\\"\\n  echo '"'"'if [ -n \\"$1\\" ]; then \\"$@\\"; else /usr/bin/env bash; fi'"'"' >> \\"$ND_ENTRYPOINT\\";\\nfi\\nchmod -R 777 /neurodocker && chmod a+s /neurodocker" \
      } \
    }, \
    { \
      "name": "install", \
      "kwds": { \
        "pkgs": [ \
          "graphviz", \
          "ffmpeg", \
          "libsm6", \
          "libxext6", \
          "xvfb", \
          "x11-utils" \
        ], \
        "opts": null \
      } \
    }, \
    { \
      "name": "run", \
      "kwds": { \
        "command": "apt-get update -qq \\\\\\n    && apt-get install -y -q --no-install-recommends \\\\\\n           ffmpeg \\\\\\n           graphviz \\\\\\n           libsm6 \\\\\\n           libxext6 \\\\\\n           x11-utils \\\\\\n           xvfb \\\\\\n    && rm -rf /var/lib/apt/lists/*" \
      } \
    }, \
    { \
      "name": "install", \
      "kwds": { \
        "pkgs": [ \
          "graphviz", \
          "libosmesa6", \
          "libegl1", \
          "libgl1-mesa-dri" \
        ], \
        "opts": null \
      } \
    }, \
    { \
      "name": "run", \
      "kwds": { \
        "command": "apt-get update -qq \\\\\\n    && apt-get install -y -q --no-install-recommends \\\\\\n           graphviz \\\\\\n           libegl1 \\\\\\n           libgl1-mesa-dri \\\\\\n           libosmesa6 \\\\\\n    && rm -rf /var/lib/apt/lists/*" \
      } \
    }, \
    { \
      "name": "run", \
      "kwds": { \
        "command": "micromamba install -y -n smriprep -c conda-forge '"'"'vtk>=9.3=*osmesa*'"'"' && micromamba clean --all --yes" \
      } \
    }, \
    { \
      "name": "run", \
      "kwds": { \
        "command": "micromamba install -y -n smriprep -c conda-forge '"'"'nodejs>=20'"'"' && micromamba clean --all --yes" \
      } \
    }, \
    { \
      "name": "copy", \
      "kwds": { \
        "source": [ \
          ".", \
          "/meeg-pipelines" \
        ], \
        "destination": "/meeg-pipelines" \
      } \
    }, \
    { \
      "name": "run", \
      "kwds": { \
        "command": "micromamba run -n smriprep pip install --no-cache-dir -e /meeg-pipelines[all]" \
      } \
    }, \
    { \
      "name": "copy", \
      "kwds": { \
        "source": [ \
          "./docker/entrypoint.sh", \
          "/usr/local/bin/entrypoint.sh" \
        ], \
        "destination": "/usr/local/bin/entrypoint.sh" \
      } \
    }, \
    { \
      "name": "run", \
      "kwds": { \
        "command": "chmod +x /usr/local/bin/entrypoint.sh" \
      } \
    }, \
    { \
      "name": "entrypoint", \
      "kwds": { \
        "args": [ \
          "/usr/local/bin/entrypoint.sh" \
        ] \
      } \
    }, \
    { \
      "name": "run", \
      "kwds": { \
        "command": "mkdir -p /out /scratch" \
      } \
    } \
  ] \
}' > /.reproenv.json
# End saving to specification to JSON.
