.. This (-*- rst -*-) format file contains commonly used link targets and name
   substitutions.  It may be included in many files, therefore it should only
   contain link targets and name substitutions. Try grepping for "^\.\. _" to
   find plausible candidates for this list.

.. NOTE: reST targets are
   __not_case_sensitive__, so only one target definition is needed for:
   nipy, NIPY, Nipy, etc...


.. project

.. _project github: https://github.com/vferat/meeg-pipelines
.. _project citation: https://github.com/vferat/meeg-pipelines/blob/main/CITATION.cff
.. _project license: https://github.com/vferat/meeg-pipelines/blob/main/LICENSE


.. license

.. _MIT license: https://opensource.org/licenses/MIT


.. mne

.. _mne stable: https://mne.tools/stable/index.html
.. _mne bids: https://mne.tools/mne-bids/stable/index.html

